name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests (spec-compliant)
      run: cargo test --verbose

    - name: Run tests (noncompliant feature)
      run: cargo test --verbose --features noncompliance
